version: '3'
services:
  soccer-team-manager:
    image: node:16
    container_name: nodeContainer
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /soccer-team-manager
    volumes:
      - ./:/soccer-team-manager